
EDIP_closeOpenEditor=function(){if(Widgets.EditInPlace&&Widgets.EditInPlace.currentEditElement){var _1=Widgets.EditInPlace.currentEditElement;if(Widgets.EditInPlace.elements){var _2=Widgets.EditInPlace.elements[_1];}
if(_2&&_2.autoExit){_2.autoExit.call(_2,true);}}};if(typeof Widgets=="undefined"){Widgets={};}
Widgets.EditInPlace=Class.create();Widgets.EditInPlace.currentEditElement="";Widgets.EditInPlace.elements={};Widgets.EditInPlace.li=null;Widgets.EditInPlace.nowSaving=false;Widgets.EditInPlace.prototype={initialize:function(id,pk,_5){this.id=id;this.pk=pk;this.options=_5;this.divElement=null;this.ownListeners=null;this.parentListeners=null;this.origValue="";this.focusStatus=false;var _6=new Kore.JSLoader();_6.addFile("includes/yui/yahoo/yahoo.js");_6.addFile("includes/yui/dom/dom.js");_6.addFile("includes/yui/event/event.js");_6.addFile("includes/yui/animation/animation.js");_6.addFile("includes/yui/connection/connection.js");_6.addFile("includes/kore/js/error.js");_6.addFile("includes/kore/js/browser/browser.js");_6.addFile("includes/kore/js/dataprovider/transporter.js");_6.addFile("includes/kore/js/dataprovider/dataprovider.js");_6.addFile("includes/kore/js/dataprovider/jsonprovider.js");_6.addFile("includes/kore/js/loadingindicator/loadingindicator.js");try{_6.loadFiles(function(){if(!Kore.isOkForAjax()){return false;}
var _7=new Kore.CSSLoader();_7.addFile("includes/jaxon/css/loading.css");_7.loadFiles(function(){Kore.addUnloadListener(this.unload,this,true);this.initEditInPlace();}.bind(this));}.bind(this));_6=null;}
catch(e){}},initEditInPlace:function(){Widgets.EditInPlace.li=Kore.LoadingIndicator.create();var _8="editinplace_"+this.id+"_"+this.pk;var _9=YAHOO.util.Dom.get(_8);YAHOO.util.Event.addListener(_9,"mousedown",function(){this.lockTargetElement(_9);},this,true);YAHOO.util.Event.addListener(_9,"mouseover",function(){this.showOverlay(_9,true);},this,true);YAHOO.util.Event.addListener(_9,"mouseout",function(){this.showOverlay(_9,false);},this,true);YAHOO.util.Event.addListener(_9,"click",function(){this.changeToEditable();},this,true);},lockTargetElement:function(_a){this.divElement=_a;},showOverlay:function(_b,_c){if(!_c){YAHOO.util.Dom.removeClass(_b,"over_edittext");_b.title="";}else{YAHOO.util.Dom.addClass(_b,"over_edittext");if(this.options.click){_b.title=this.options.click;}}},changeToEditable:function(){var _d=this.divElement;var _e=_d.id;if(Widgets.EditInPlace.currentEditElement==_e){return;}
if(Widgets.EditInPlace.currentEditElement){var _f=Widgets.EditInPlace.currentEditElement;var _10=Widgets.EditInPlace.elements[_f];if(_10){_10.autoExit(_f,true);}}
var _11=this.handleEmpty(_d.innerHTML);var _12=""+"<textarea id=\""+_d.id+"_textarea\" "+"class=\"editable_textarea\">"+_11+"</textarea>"+"<div>"+"<a href=\"#\" id=\""+_d.id+"_save\" "+"class=\"editlink\">"+this.options.save+"</a> "+"<a href=\"#\" id=\""+_d.id+"_cancel\" "+"class=\"editlink\">"+this.options.cancel+"</a>"+"</div>";_d.innerHTML=_12;var _13=YAHOO.util.Dom.get(_e+"_textarea");var _14=YAHOO.util.Dom.get(_e+"_save");var _15=YAHOO.util.Dom.get(_e+"_cancel");YAHOO.util.Event.addListener(_14,"click",this.updateValue,this,true);YAHOO.util.Event.addListener(_15,"click",this.cancelEdit,this,true);YAHOO.util.Event.addListener(_13,"focus",this.captureFocus,this,true);YAHOO.util.Event.addListener(_14,"focus",this.captureFocus,this,true);YAHOO.util.Event.addListener(_15,"focus",this.captureFocus,this,true);YAHOO.util.Event.addListener(_13,"blur",this.captureBlur,this,true);YAHOO.util.Event.addListener(_14,"blur",this.captureBlur,this,true);YAHOO.util.Event.addListener(_15,"blur",this.captureBlur,this,true);Widgets.EditInPlace.currentEditElement=_e;this.origValue=_11;this.purgeEditEl();_13.focus();_13.select();if(!Widgets.EditInPlace.elements[_e]){Widgets.EditInPlace.elements[_e]=this;}},handleEmpty:function(_16){if(_16.toLowerCase()==this.options.empty.toLowerCase()){return("");}
var _17=/[^\s]/;if(!_17.test(_16)){return(this.options.empty);}
return _16;},updateValue:function(evt){Widgets.EditInPlace.nowSaving=true;if(evt){YAHOO.util.Event.stopEvent(evt);}
var _19=this.divElement;var _id=_19.id;Widgets.EditInPlace.li.start();var _1b=_id+"_textarea";var _1c=YAHOO.util.Dom.get(_1b);var _1d=_1c.value;var _1e=Kore.getDocumentCharset();var _1f=_1e.toLowerCase()=="iso-8859-1"?escape:encodeURIComponent;var _20=_1f(_1d);var _21=this;window[this.id+"_updateValue"](this.pk,"POST-DATA","edit_value="+_20,function(_22,_23){Widgets.EditInPlace.li.stop();var _24=_23[0];if(_24.error){_24.error.show("Error no: %s has occured: \"%s"+"\" while executing query to URL: \""+_24.URL+"\".");}else{if(_24.content.error){Kore.Log.info(_24.content.error.code+": "+_24.content.error.message);_1c.focus();}else{var _25=_24.content;if(_25=="OK"){if(!/[^\s]/.test(_1d)){_1d=_21.options.empty;}
_19.innerHTML=_1d;_21.unPurgeElement(_19);_21.cleanup();}}}});Widgets.EditInPlace.nowSaving=false;},cancelEdit:function(evt,_27){if(evt){YAHOO.util.Event.stopEvent(evt);}
var _28=this.divElement;_28.innerHTML=this.handleEmpty(this.origValue);this.unPurgeElement(_28);if(_27===true){return;}
this.cleanup();},purgeEditEl:function(){var _29=this.divElement;var _2a=_29.parentNode;this.ownListeners=YAHOO.util.Event.getListeners(_29);this.parentListeners=YAHOO.util.Event.getListeners(_2a);this.fireMouseEvent(_29,"mouseout");YAHOO.util.Event.purgeElement(_29);this.fireMouseEvent(_2a,"mouseout");YAHOO.util.Event.purgeElement(_2a);},unPurgeElement:function(){var _2b=function(_2c,_2d){for(var i=0;i<_2d.length;i++){var _2f=_2d[i];YAHOO.util.Event.addListener(_2c,_2f.type,_2f.fn,_2f.adjust,true);}};var _30=this.divElement;_2b(_30,this.ownListeners);if(this.parentListeners){var _31=_30.parentNode;_2b(_31,this.parentListeners);}},fireMouseEvent:function(_32,_33){var _34=YAHOO.util.Event.getListeners(_32);if(!_34){return;}
for(var i=0;i<_34.length;i++){var _36=_34[i];if(_36.type.toLowerCase()==_33){_36.fn.call(_36.adjust);}}},captureBlur:function(evt){var _38=this.divElement;var _id=_38.id;this.focusStatus=false;if(typeof exitTimer=="number"){window.clearTimeout(this.exitTimer);}
exitTimer=window.setTimeout(function(){this.autoExit();}.bind(this),100,_id);},captureFocus:function(){this.focusStatus=true;},autoExit:function(_3a){if(Widgets.EditInPlace.nowSaving){return;}
if(_3a||!this.focusStatus){switch(this.options.blurAction){case"save":this.updateValue();break;case"cancel":this.cancelEdit();break;default:if(_3a){this.cancelEdit(false,true);}
break;}}},sesCompleteEffect:function(){var _3b=this.divElement;this.fireMouseEvent(_3b,"mouseover");this.fireMouseEvent(_3b.parentNode,"mouseover");window.setTimeout(function(){this.fireMouseEvent(_3b,"mouseout");this.fireMouseEvent(_3b.parentNode,"mouseout");}.bind(this),500);},cleanup:function(){this.sesCompleteEffect();window.setTimeout(function(){Widgets.EditInPlace.currentEditElement="";}.bind(this),100);},unload:function(){$H(Widgets.EditInPlace.elements).each(function(_3c){var key=_3c[0];var _3e=_3c[1];if(key!="_break"){var _3f=_3e.divElement;YAHOO.util.Event.purgeElement(_3f);}});Widgets.EditInPlace.elements={};}};