
if(typeof Widgets=="undefined"){Widgets={};}
Widgets.general_actions={addActions:function(o){o.processURL=Widgets.general_actions.processURL;o.checkTarget=Widgets.general_actions.checkTarget;o.initForms=Widgets.general_actions.initForms;o.initLinks=Widgets.general_actions.initLinks;},initLinks:function(){var _2=$A(this.domElement.getElementsByTagName("a"));_2.each(function(_3){if(_3.getAttribute("ajaxified")==null){_3.setAttribute("ajaxified","true");if(this.checkTarget(_3.href,this.fullUrl)){_3.href=this.processURL(_3.href);new AjaxLink(_3,this);}}}.bind(this));},initForms:function(){var _4=$A(this.domElement.getElementsByTagName("form"));_4.each(function(_5){if(_5.getAttribute("ajaxified")==null){_5.setAttribute("ajaxified","true");if(this.checkTarget(_5.action,this.fullUrl)){if(_5.enctype.toLowerCase()!="multipart/form-data"){if(_5.method.toLowerCase()!="get"){_5.action=this.processURL(_5.action);}
new AjaxForm(_5,this);}else{_5.action=this.processURL(_5.action);}}}}.bind(this));},checkTarget:function(_6,_7){var _8=decodeURI(_6);var _9=decodeURI(_7.replace(/\?.*$/,""));if(_8.indexOf("#")!=-1){return false;}
if(_8.indexOf("/")==-1){_8=_9.replace(/\/[^\/]*$/,"/"+_8);}else{if(_8.indexOf("/")==0){_8=_9.replace(/^([^\/]+\/\/[^\/]+)\/.*$/,"$1"+_8);}}
return(_8.indexOf(_9)==0);},processURL:function(_a){if(_a.indexOf("KT_ajax_request=true")>=0){_a=_a.replace(/&KT_ajax_request=true/,"");_a=_a.replace(/\?KT_ajax_request=true$/,"");_a=_a.replace(/\?KT_ajax_request=true&/,"?");}
return _a;}};function AjaxForm(_b,_c){this.form=_b;this.form.dialog=_c;if(typeof GLOBAL_registerFormSubmitEventHandler!="undefined"){GLOBAL_registerFormSubmitEventHandler("AjaxForm_handleFormSubmit",50,this.form);}else{YAHOO.util.Event.addListener(this.form,"submit",AjaxForm_handleFormSubmit,this,true);}}
function AjaxForm_handleFormSubmit(e){var _e;if(typeof fire_starter=="undefined"||(typeof fire_starter!="undefined"&&!fire_starter)){_e=YAHOO.util.Event.getTarget(e);}else{_e=fire_starter;}
if(_e.form){_e=_e.form;}
var _f=_e.action;if(_e.method=="get"){var _f=$app_path+"?"+Form.serialize(_e);_e.dialog.setUrl(_f);_e.dialog.loadInfo();}else{var _f=_e.action;_e.dialog.setUrl(_f);_e.dialog.loadInfo({method:"post",postData:Form.serialize(_e)});}
YAHOO.util.Event.stopEvent(e);return false;}
function AjaxLink(_10,_11){this.link=_10;this.link.dialog=_11;YAHOO.util.Event.addListener(YAHOO.util.Dom.get(this.link),"click",function(e){var url=YAHOO.util.Dom.get(this.link).href;this.link.dialog.setUrl(url);this.link.dialog.loadInfo();YAHOO.util.Event.stopEvent(e);return false;},this,true);}