
if(typeof MxAjaxToolbox=="undefined"){MxAjaxToolbox={};}
MxAjaxToolbox.MultiHtmlProvider=Class.create();MxAjaxToolbox.MultiHtmlProvider.prototype=Object.extend(new Kore.DataProvider(),{processors:null,descriptor:null,html_content:null,contents:null,beforeLoadEvent:null,initialize:function(_1,_2){this.URL=_1?_1:null;this.contents={};this.processors={};this.setOptions(_2);this.updateEvent=new YAHOO.util.CustomEvent("update",this);this.finalizeEvent=new YAHOO.util.CustomEvent("finalize",this);this.startEvent=new YAHOO.util.CustomEvent("start",this);this.beforeLoadEvent=new YAHOO.util.CustomEvent("beforeLoad",this);},parseRawResponse:function(){this.descriptor=null;this.html_content=null;try{var _3=this.transport.getResponseHeader["Kt_json"];if(typeof(_3)=="undefined"){this.error=new Kore.Error(Kore.Error.ERR_NOT_JSON,"Error processing server response:"+"\r\n================================\r\n"+this.transport.responseText+"\r\n================================");return;}
this.descriptor=eval("("+_3+")");}
catch(e){this.error=new Kore.Error(Kore.Error.ERR_NOT_JSON,e.message);return;}
if(!this.content){this.error=new Kore.Error(Kore.Error.ERR_NOT_HTML,"The HTML content is missing.");return;}
this.html_content=this.content;try{if(typeof document.selection!="undefined"){document.selection.empty();}else{window.getSelection().collapseToStart();}}
catch(e){}
for(fragment_id in this.descriptor.panels){if(typeof this.descriptor.panels[fragment_id].end!="undefined"){this.contents[fragment_id]=this.html_content.substring(this.descriptor.panels[fragment_id].start,this.descriptor.panels[fragment_id].end);}else{this.contents[fragment_id]=this.html_content.substr(this.descriptor.panels[fragment_id].start);}
var s=this.contents[fragment_id];var _5="<div class=\"panel__content\">";var _6="</div>";if(s.indexOf(_5)>=0){s=s.replace(new RegExp(_5,"i"),"");var _7=s.lastIndexOf(_6);if(_7>=0){var _8=s.substr(0,_7);if(_8.trim().length!=0){s=_8+s.substr(_7+6,s.length);}else{s="";}}}else{}
this.contents[fragment_id]=s;}},initializeProcessors:function(){this.num_processors_loaded=0;this.num_processors_ready=0;this.num_processors=0;for(var _9 in $ctrl.panels){if(typeof this.descriptor.panels[_9]!="undefined"){if(this._isEmptyContent(this.contents[_9])){YAHOO.util.Dom.setStyle($ctrl.getPanel(_9).getHTMLElement(),"display","none");}else{YAHOO.util.Dom.setStyle($ctrl.getPanel(_9).getHTMLElement(),"display","");}
this.num_processors++;this.processors[_9]=new Kore.HtmlProcessor($ctrl.panels[_9],this.contents[_9],_9);this.processors[_9].fireLegacyOnLoad=false;this.processors[_9].container.loadEvent.subscribe(this.legacyOnLoad,this,true);var p=$ctrl.panels[_9];this.processors[_9].beforeLoadEvent.subscribe(p.handleStartEffect,p,true);}}},_isEmptyContent:function(_b){return _b=="";},processorReady:function(_c,_d){_d=_d[0];this.num_processors_ready++;_d.handleEndEffect();if(this.num_processors_ready==this.num_processors){this.finalizeEvent.fire();}},onComplete:function(){this.parseRawResponse();if(this.error){this.error.show();this.finalizeEvent.fire();return;}
this.initializeProcessors();this.finalizeEvent.subscribe(function(){if(this.descriptor!=null&&this.descriptor.title){document.title=this.descriptor.title;}},this,true);for(var _e in this.processors){var _f=$ctrl.panels[_e];_f.setCurrentState(this.descriptor.panels[_f.name].current_state);this.processors[_e].addFinalizeListener(this.processorReady,this,true);this.processors[_e].process();}},legacyOnLoad:function(){this.num_processors_loaded++;if(this.num_processors_loaded!=this.num_processors){return;}
try{var _10="load";if(typeof window.__eventHandlers!="undefined"&&typeof window.__eventHandlers[_10]!="undefined"){for(var i=0;i<window.__eventHandlers[_10].length;i++){var f=window.__eventHandlers[_10][i];f();}}}
catch(e){alert(e.message);}}});