
Controller=Class.create();Controller.prototype={initialize:function(fn){this.panels={};this.js_loaded=false;this.page_loaded=false;this.readyEvents=[];this.initCallback=fn;this.masterPanel=null;var _2=new Kore.JSLoader();_2.addFile("includes/kore/js/error.js");_2.addFile("includes/kore/js/browser/browser.js");_2.addFile("includes/kore/js/JSON.js");_2.addFile("includes/yui/yahoo/yahoo.js");_2.addFile("includes/yui/dom/dom.js");_2.addFile("includes/yui/event/event.js");_2.addFile("includes/yui/connection/connection.js");_2.addFile("includes/yui/animation/animation.js");_2.addFile("includes/kore/js/history/dhtmlHistory.js");_2.addFile("includes/kore/js/dataprovider/transporter.js");_2.addFile("includes/kore/js/dataprovider/htmlprocessor.js");_2.addFile("includes/kore/js/dataprovider/dataprovider.js");_2.addFile("includes/jaxon/js/multihtmlprovider.js");_2.addFile("includes/kore/js/loadingindicator/loadingindicator.js");_2.loadFiles(function(){if(!Kore.isOkForAjax()){return false;}
this.relPath=_2.relPath;if(this.page_loaded){this.initializeAfterLoad();}else{YAHOO.util.Event.addListener(window,"load",this.initializeAfterLoad,this,true);}}.bind(this));},initializeAfterLoad:function(){try{this.li=Kore.LoadingIndicator.create();window.historyStorage.init();window.dhtmlHistory.create(this.relPath+"includes/jaxon/js/blank.html");this.initCallback();for(var i=0;i<this.readyEvents.length;i++){this.readyEvents[i]();}
this.js_loaded=true;}
catch(e){alert(e);}},createPanel:function(_4){var _5=new Panel(_4,this);if(typeof(this.panels[_4])=="undefined"){this.panels[_4]=_5;}
return _5;},setMasterPanel:function(_6){this.masterPanel=_6;},getPanel:function(_7){return this.panels[_7]||null;},addReadyEvent:function(fn){if(this.js_loaded){fn();}else{this.readyEvents.push(fn);}
this.page_loaded=true;},loadPanels:function(_9,_a){dhtmlHistory.toAdd=_9;_9=_9+(_9.indexOf("?")>=0?"&KT_ajax_request=true":"?KT_ajax_request=true");var _b=new MxAjaxToolbox.MultiHtmlProvider(_9,_a);_b.startEvent.subscribe(this.li.start,this.li,true);_b.finalizeEvent.subscribe(this.li.stop,this.li,true);_b.finalizeEvent.subscribe(function(){var _c=dhtmlHistory.toAdd;if(_c.indexOf("?")>=0){_c=_c.replace(/^.*\?/,"#");}else{_c="";}
dhtmlHistory.add(_c,["Controller.historyChanged",""]);},this,true);_b.getContent();},refreshPanels:function(){var _d=window.location.toString();_d=_d.replace(/#/,"?");_d=_d.replace(/\?.*\?/,"?");this.loadPanels(_d);}};Controller.initializeHistory=function(){dhtmlHistory.initialize();if(dhtmlHistory.isFirstLoad()){var _e=window.location.href.toString();if(_e.indexOf("#")>=0){_e=_e.substring(_e.lastIndexOf("#")+1);if(_e.length!=0){Controller.historyChanged(_e);}}else{historyStorage.put("",["Controller.historyChanged",""]);}}};Controller.historyChanged=function(_f){$ctrl.loadPanels($app_path+"?"+_f);};Controller.checkTarget=function(url,_11){var _12=decodeURI(url);var _13=decodeURI(_11.replace(/\?.*$/,""));if(_12.indexOf("#")!=-1){return false;}
if(_12.indexOf("/")==-1){_12=_13.replace(/\/[^\/]*$/,"/"+_12);}else{if(_12.indexOf("/")==0){_12=_13.replace(/^([^\/]+\/\/[^\/]+)\/.*$/,"$1"+_12);}}
return(_12.indexOf(_13)==0);};Controller.processURL=function(url,_15){var _16=false;if(url.indexOf("KT_ajax_request=true")>=0){url=url.replace(/&KT_ajax_request=true/,"");url=url.replace(/\?KT_ajax_request=true$/,"");url=url.replace(/\?KT_ajax_request=true&/,"?");_16=true;}
var _17=_15.name+"__state=";var _18="__state=";var _19=false;if(url.indexOf(_18)<0){_19=true;}else{if(_16&&url.indexOf(_17)<0){_19=true;}}
if(_19){url+=(url.indexOf("?")>=0?"&":"?")+_15.name+"__state="+_15.currentState;}
return url;};Controller.initForms=function(_1a){var _1b=$ctrl.getPanel(_1a);var _1c=_1b.getContentHTMLElement();var _1d=$A(_1c.getElementsByTagName("form"));_1d.each(function(_1e){if(_1e.getAttribute("ajaxified")==null){_1e.setAttribute("ajaxified","true");if(Controller.checkTarget(_1e.action,$app_path)){if(_1e.enctype.toLowerCase()!="multipart/form-data"){if(_1e.method.toLowerCase()=="get"){var _1f=true;for(var i=0;i<_1e.elements.length;i++){if(_1e.elements[i].name.match(/__state$/)){_1f=false;break;}}
if(_1f){var el=document.createElement("input");el.name=_1a+"__state";el.value=_1b.currentState;el.type="hidden";_1e.appendChild(el);}}else{_1e.action=Controller.processURL(_1e.action,_1b);}
new PanelForm(_1e,{"panel":_1a});}else{_1e.action=Controller.processURL(_1e.action,_1b);}}}});};Controller.initLinks=function(_22){var _23=$ctrl.getPanel(_22);var _24=_23.getContentHTMLElement();var _25=$A(_24.getElementsByTagName("a"));_25.each(function(_26){if(_26.getAttribute("ajaxified")==null){_26.setAttribute("ajaxified","true");if(Controller.checkTarget(_26.href,$app_path)){if(_26.id.indexOf("link__")!=0){if(_26.id==""){_26.id="link__"+(Math.random()).toString().replace(/\./,"");}
_26.href=Controller.processURL(_26.href,_23);new PanelLink(_26.id,{"panel":_22});}}}});};function Panel(_27){this.name=_27;this.states={};this.titles={};this.objects=[];this.updateEffect="";this.currentState="";this.setUpdateEffect=function(_28){if(Kore.is.safari&&_28=="fade"){_28="";}
this.updateEffect=_28;};this.getHTMLElement=function(){return YAHOO.util.Dom.get("__"+this.name);};this.getContentHTMLElement=function(){var dv=this.getHTMLElement();var c=YAHOO.util.Dom.getElementsByClassName("panel__content","div",dv);return c[0];};this.domElement=this.getContentHTMLElement();this.addState=function(_2b,_2c,_2d){this.states[_2b]=_2c;this.titles[_2b]=_2d;};this.setCurrentState=function(_2e){this.currentState=_2e;};this.handleStartEffect=function(){if(this.updateEffect=="fade"){YAHOO.util.Dom.setStyle(this.domElement,"opacity",0);}
if(this.updateEffect=="delay"){YAHOO.util.Dom.setStyle(this.domElement,"opacity",0);}};this.handleEndEffect=function(){if(this.updateEffect=="fade"||this.updateEffect=="delay"){if(Kore.is.ie){var el=this.domElement;var bg="";var _31="";if(el.currentStyle){_31=el.currentStyle.backgroundColor;}
while(el){if(el.currentStyle){bg=el.currentStyle.backgroundColor;if(bg!=""&&bg!="transparent"){break;}}
el=el.parentElement;}
if(bg=="transparent"){bg="";}
YAHOO.util.Dom.setStyle(this.domElement,"background-color",bg||"#FFF");}}
if(this.updateEffect=="fade"){var _32=new YAHOO.util.Anim(this.domElement,{opacity:{to:1}},1);if(Kore.is.ie&&Kore.is.v<7){_32.onComplete.subscribe(function(){this.domElement.style.filter="";YAHOO.util.Dom.setStyle(this.domElement,"background-color",_31);},this,true);}
_32.animate();}
if(this.updateEffect=="delay"){var _32=new YAHOO.util.Anim(this.domElement,{opacity:{to:1}},0.3,function(t,b,c,d){if(t<d){return b;}
return b+c;});if(Kore.is.ie&&Kore.is.v<7){_32.onComplete.subscribe(function(){this.domElement.style.filter="";YAHOO.util.Dom.setStyle(this.domElement,"background-color",_31);},this,true);}
_32.animate();}};this.loadEvent=new YAHOO.util.CustomEvent("load",this);this.unloadEvent=new YAHOO.util.CustomEvent("unload",this);}
function PanelLink(_37,_38){this.htmlElement=_37;this.options=_38;YAHOO.util.Event.addListener(YAHOO.util.Dom.get(this.htmlElement),"click",function(e){if(typeof e_PanelLink_stop!="undefined"){if(e_PanelLink_stop){delete e_PanelLink_stop;YAHOO.util.Event.stopEvent(e);return false;}else{delete e_PanelLink_stop;}}
var url=YAHOO.util.Dom.get(this.htmlElement).href;$ctrl.loadPanels(url);YAHOO.util.Event.preventDefault(e);return false;},this,true);if(this.options.panel){$ctrl.panels[this.options.panel].unloadEvent.subscribe(this.unload,this,true);}}
PanelLink.prototype={unload:function(){YAHOO.util.Event.purgeElement(YAHOO.util.Dom.get(this.htmlElement));this.options=null;}};function PanelForm_handleFormSubmit(e){var _3c;if(typeof fire_starter=="undefined"||(typeof fire_starter!="undefined"&&!fire_starter)){_3c=YAHOO.util.Event.getTarget(e);}else{_3c=fire_starter;}
if(_3c.form){_3c=_3c.form;}
var url=_3c.action;if(_3c.method.toLowerCase()=="get"){var url=$app_path+"?"+Form.serialize(_3c);$ctrl.loadPanels(url);}else{var url=_3c.action;$ctrl.loadPanels(url,{method:"post",postData:Form.serialize(_3c)});}
YAHOO.util.Event.stopEvent(e);return false;}
function PanelForm_overrideSubmit(){var url=this.action;var _3f=this.method.toLowerCase();if(_3f=="get"){var url=$app_path+"?"+Form.serialize(this);$ctrl.loadPanels(url);}else{var url=this.action;$ctrl.loadPanels(url,{method:"post",postData:Form.serialize(this)});}
return false;}
function PanelForm(_40,_41){this.form=_40;this.options=_41;if(typeof GLOBAL_registerFormSubmitEventHandler!="undefined"){GLOBAL_registerFormSubmitEventHandler("PanelForm_handleFormSubmit",50,this.form);}else{YAHOO.util.Event.addListener(this.form,"submit",PanelForm_handleFormSubmit,this,true);}
$ctrl.panels[this.options.panel].unloadEvent.subscribe(this.unload,this,true);}
PanelForm.prototype={unload:function(){YAHOO.util.Event.purgeElement(this.form,false);delete this.form;}};function PanelTooltip(_42,_43,_44,_45,_46){this.relatedLinkID=_42;this.panel=_43;this.state=_44;this.parameters=_45;this.dims=_46;var _47=new Kore.JSLoader();_47.addFile("includes/kore/js/dataprovider/htmlprovider.js");_47.addFile("includes/jaxon/widgets/tooltip/js/tooltip.js");_47.loadFiles(function(){new Widgets.Tooltip(this.relatedLinkID,this.panel,this.state,this.parameters,this.dims);}.bind(this));}
function PanelLink_confirm(str){if(confirm(str)){e_PanelLink_stop=false;}else{e_PanelLink_stop=true;}
return e_PanelLink_stop;}