<?php
// include the base class
require_once(CONN_DIR.'/../tNG/KT_tNG.inc.php');


define('MULTIPLE_DELETE_TYPE','MultipleDelType');

//class interface
class KT_tNG_mdel extends KT_tNG {

	var $uniqueKeyValues; //array

	/**
	RST - set the unique key
	$i_keyName = string (name of the key)
	$i_keyValues = (values array of the key)
	$i_keyQuote = unique Key Data Type
	**/
	function setUniqueKeyMultiValues($i_keyName,$i_keyValues,$i_keyType) {
		$this->uniqueKey = $i_keyName;
		$this->uniqueKeyValues = $i_keyValues;
		$this->uniqueKeyType = $i_keyType;
	}

	function prepareSQL() {
		if ($this->type == MULTIPLE_DELETE_TYPE){
			$this->generateSQL();
		}
	}

	/**
	Generates the SQL of the transaction based on the previos gathered informations (columns names,types,values)
	**/
	function generateSQL() {
		//escape quotes
		for ($idxCol = 0;$idxCol < count($this->columnsValue);$idxCol++) {
			if (isset($this->columnsValue[$idxCol])) {
				$tmp = $this->connection->qstr($this->columnsValue[$idxCol],false);
				$this->columnsValue[$idxCol] = substr($tmp,1,strlen($tmp) - 2);
			}
		}
		//check the type of the transaction and call the apropiate method
		switch ($this->type) {
			case MULTIPLE_DELETE_TYPE:
					$this->generateMultipleDeleteSQL();
					break;
			default: // if it isn't an autogenerated type set an error
				$this->errorNo = KT_NO_AUTO_TYPE;
				$this->errorMsg = 'No autogenerated type!';
		}
	}	

	/**
	RST - generate in part of the statement 
	**/
	function generateInPart() {
		$keyQuote = $this->type2quote[$this->uniqueKeyType];
		$n = count($this->uniqueKeyValues);
		$inPart = ' (';
		for ($i = 0;$i <$n;$i++) {
			$inPart = $inPart . $keyQuote . $this->uniqueKeyValues[$i] . $keyQuote;
			if($i < $n-1) {
				$inPart .= ', ';
			}
		}
		$inPart .= ') ';
		return $inPart;
	}

	/**
	RST - generate Multiple Delete SQL 
	**/
	function generateMultipleDeleteSQL() {
		if (($this->table) && ($this->uniqueKey) && ($this->uniqueKeyValues)) {
			$this->SQL = 'delete from ' . $this->table . ' where ' . $this->uniqueKey . ' in ';
			$this->SQL = $this->SQL . $this->generateInPart();
		} else {
			$this->errorNo = KT_NO_PARAMS_DELETE_SQL;
			$this->errorMsg = "Not enough parameters to generate multiple delete SQL!";
		}
	}
	

}

?>