
if(!Kore){var Kore={};}
Kore.HtmlProcessor=Class.create();Kore.HtmlProcessor.prototype={container:null,source:null,hideContainerIfEmpty:false,fireLegacyOnLoad:true,error:null,scripts:[],styles:[],writeString:null,initialize:function(_1,_2){this.hideContainerIfEmpty=false;this.fireLegacyOnLoad=true;this.container=_1;if(typeof _1.loadEvent=="undefined"){this.container.loadEvent=new YAHOO.util.CustomEvent("load",this.container);this.container.unloadEvent=new YAHOO.util.CustomEvent("unload",this.container);}
this.source=_2;this.js_loader=new Kore.JSLoader(false);this.css_loader=new Kore.CSSLoader(false);this.scripts=[];this.styles=[];this.finalizeEvent=new YAHOO.util.CustomEvent("finalize",this);this.beforeLoadEvent=new YAHOO.util.CustomEvent("beforeLoad",this);this.writeString="";},getAllScripts:function(){var _3=/(<script[^>]*>((?:.|\r|\n|\r\n)*?)<\/script>)/gi;while((arr_to_load=_3.exec(this.source))!=null){var _4=arr_to_load[1];var _5=_4.match(/src="([^"]*)"/);if(_5){var _6=_5[1];var _7=window.location.toString().replace(/\/[^\/]*$/gi,"/");_6=_7+_6;this.scripts.push({"type":"src","src":_6,"content":null,"position":arr_to_load.index});}else{var _8=_4.replace(/<script[^>]*>/i,"");_8=_8.replace(/<\/script>/i,"");if(_8.trim()!=""){this.scripts.push({"type":"inline","src":null,"content":_8,"position":arr_to_load.index});}}}
var _9=this.source;var _a=0;for(var i=0;i<this.scripts.length;i++){var _c=this.scripts[i].position+_a;var _d="<span koreid=\"k"+i+"\"></span>";_9=_9.substr(0,_c)+_d+_9.substr(_c);_a+=_d.length;}
this.source=_9;},getAllStyleSources:function(){if(Kore.is.ie||Kore.is.safari){var _e=window.location.toString().replace(/\/[^\/]*$/gi,"/");var _f=null;var _10=this.source.match(/<link[^>]*>|<style[^>]*>((?:.|\r|\n|\r\n)*?)<\/style>/gi);if(_10!=null&&_10.length){for(var i=0;i<_10.length;i++){_f=_10[i].match(/href="([^\"]*)"/i);if(_f&&_f[1]){this.styles.push({"type":"src","src":_e+_f[1],"content":null});}else{var _12=_10[i];_12=_12.replace(/<style[^>]*>/i,"");_12=_12.replace(/<\/style>/i,"");this.styles.push({"type":"inline","src":null,"content":_12});}}}}},retrieveAllScriptSources:function(){for(var i=0;i<this.scripts.length;i++){var o=this.scripts[i];if(o.type=="src"){this.js_loader.addFile(o.src);}}
this.js_loader.loadFiles(function(){this.loadAllScriptsInContainer();}.bind(this),false);},retrieveAllStyleSources:function(){for(var i=0;i<this.styles.length;i++){if(this.styles[i].type=="src"){this.css_loader.addFile(this.styles[i].src);}}
this.css_loader.loadFiles(function(){this.loadAllStylesInContainer();this.retrieveAllScriptSources();}.bind(this));},toExecute:function(_16){return Kore.Cache.getState(_16)!=Kore.Cache.States.executed;},loadAllStylesInContainer:function(){this.css_loader.doEvaluation=true;for(var i=0;i<this.styles.length;i++){var o=this.styles[i];if(o.type=="src"){this.css_loader.interpretFile(o.src);}else{this.css_loader.interpretSource(o.content);}}
this.css_loader.doEvaluation=false;},loadAllScriptsInContainer:function(){Kore.container=this.container;var _19=document.write;document.write=function(str){this.writeString+=str;}.bind(this);for(var i=0;i<this.scripts.length;i++){this.writeString="";var o=this.scripts[i];if(o.type=="src"){if(this.toExecute(o.src)){this.js_loader.interpretSource(Kore.Cache.getValue(o.src));Kore.Cache.setState(o.src,Kore.Cache.States.executed);}}else{this.js_loader.interpretSource(o.content);}
if(this.writeString.trim().length==0){continue;}
var arr=this.container.domElement.getElementsByTagName("span");for(var j=0;j<arr.length;j++){var el=arr[j];if(el.getAttribute("koreid")=="k"+i){el.innerHTML=this.writeString;break;}}}
document.write=_19;this.legacyOnLoad();this.container.loadEvent.fire();this.finalizeEvent.fire(this.container);},loadResources:function(){this.retrieveAllStyleSources();},process:function(){this.container.unloadEvent.fire();this.container.unloadEvent.unsubscribeAll();this.beforeLoadEvent.fire();this.getAllScripts();try{this.container.domElement.innerHTML=this.source;}
catch(e){this.error=new Kore.Error(Kore.Error.ERR_SETDOM,"Could not set the source on the specified element");}
if(!this.error){this.getAllStyleSources();this.loadResources();}else{this.error.show();this.finalizeEvent.fire(this.container);}},addFinalizeListener:function(fn,_21){this.finalizeEvent.subscribe(fn,_21,true);},legacyOnLoad:function(){if(!this.fireLegacyOnLoad){return;}
try{var _22="load";if(typeof window.__eventHandlers!="undefined"&&typeof window.__eventHandlers[_22]!="undefined"){for(var i=0;i<window.__eventHandlers[_22].length;i++){var f=window.__eventHandlers[_22][i];f();}}}
catch(e){alert(e.message);}}};