
if(typeof Widgets=="undefined"){Widgets={};}
Widgets.DataTable=Class.create();Widgets.DataTable.prototype={_listName:null,_listElement:null,_links:[],_form:null,initialize:function(_1){if(typeof Controller!="undefined"){return;}
this._listName=_1;this.loader=new Kore.JSLoader();this.loader.addFile("includes/yui/yahoo/yahoo.js");this.loader.addFile("includes/yui/dom/dom.js");this.loader.addFile("includes/yui/event/event.js");this.loader.addFile("includes/yui/connection/connection.js");this.loader.addFile("includes/kore/js/error.js");this.loader.addFile("includes/kore/js/browser/browser.js");this.loader.addFile("includes/kore/js/JSON.js");this.loader.addFile("includes/kore/js/history/dhtmlHistory.js");this.loader.addFile("includes/kore/js/dataprovider/transporter.js");this.loader.addFile("includes/kore/js/dataprovider/dataprovider.js");this.loader.addFile("includes/kore/js/dataprovider/htmlprovider.js");this.loader.addFile("includes/kore/js/dataprovider/htmlprocessor.js");this.loader.addFile("includes/kore/js/loadingindicator/loadingindicator.js");this.loader.loadFiles(function(){if(!Kore.isOkForAjax()){return false;}
if(Kore.is.ie&&(Kore.is.version==6)){try{document.execCommand("BackgroundImageCache",false,true);}
catch(e){}}
Kore.addUnloadListener(this.unload,this);if(Kore.container!=null&&Kore.container.objects!=null){Kore.container.objects.push(this);}
this._deferredInit();}.bind(this));},unload:function(){delete Widgets.DataTable.li;for(var i=0;i<this._links.length;i++){delete this._links[i];}},_deferredInit:function(){var _3=YAHOO.util.Dom.get(this._listName);if(_3==null){YAHOO.util.Event.addListener(window,"load",this._deferredInit,this,true);return;}
this._listElement=_3;this.app_path=window.location.href.replace(/\?.*$/,"");this.app_path=this.app_path.replace(/#.*$/,"");Widgets.DataTable.li=Kore.LoadingIndicator.create();this._initLinks();if(this._initForm()){window.historyStorage.init();window.dhtmlHistory.create();dhtmlHistory.initialize();this._initHistory();}},_initHistory:function(){var _4=window.location.href.toString();if(_4.indexOf("#")>=0){_4=_4.substring(_4.lastIndexOf("#")+1);if(_4.length!=0){Widgets.DataTable.historyChanged(_4,this._listName);}}else{historyStorage.put("",["Widgets.DataTable.historyChanged",this._listName]);}},_initLinks:function(){var _5=this._listElement.getElementsByTagName("a");for(var i=0;i<_5.length;i++){var _7=_5[i];if(_7.getAttribute("ajaxified")==null){_7.setAttribute("ajaxified","true");if(this.checkTarget(_7.href,this.app_path)){if(_7.id==""){_7.id="link__"+(Math.random()).toString().replace(/\./,"");}
this._links.push(new Widgets.DataTableLink(_7,this._listElement,this._listName));}}}},_initForm:function(){var _8=this._listElement;var _9=false;if(_8.getAttribute("ajaxified")==null){_8.setAttribute("ajaxified","true");if(this.checkTarget(_8.action,this.app_path)){if(_8.enctype.toLowerCase()!="multipart/form-data"){if(_8.method=="get"){if(typeof GLOBAL_registerFormSubmitEventHandler!="undefined"){GLOBAL_registerFormSubmitEventHandler("Widgets.DataTable.handleFormSubmit",50,_8);}else{YAHOO.util.Event.addListener(_8,"submit",Widgets.DataTable.handleFormSubmit,this,true);}
_9=true;}}}}
return _9;},checkTarget:function(_a,_b){var _c=decodeURI(_a);var _d=decodeURI(_b);if(_c.indexOf("#")!=-1){return false;}
if(_c.indexOf("/")==-1){_c=_d.replace(/\/[^\/]*$/,"/"+_c);}else{if(_c.indexOf("/")==0){_c=_d.replace(/^([^\/]+\/\/[^\/]+)\/.*$/,"$1"+_c);}}
return(_c.indexOf(_d)==0);}};Widgets.DataTableLink=Class.create();Widgets.DataTableLink.prototype={initialize:function(_e,_f,_10){this._linkElement=_e;this.domElement=_f;this._listName=_10;var url=_e.href;if(url.indexOf("KT_ajax_request=true")>=0){url=url.replace(/&KT_ajax_request=true/,"");url=url.replace(/\?KT_ajax_request=true$/,"");url=url.replace(/\?KT_ajax_request=true&/,"?");}
if(url.indexOf("KT_data_request")>=0){url=url.replace(/&KT_data_request=[^&]*/,"");url=url.replace(/\?KT_data_request=[^&]*$/,"");url=url.replace(/\?KT_data_request=[^&]*&/,"?");}
this._linkElement.href=url;YAHOO.util.Event.addListener(this._linkElement,"click",function(e){var url=this._linkElement.href;var _14=url;url=url+((url.indexOf("?")<0)?"?":"&")+"KT_data_request="+this._listName;var _15=new Kore.HtmlProvider(null,this);_15.finalizeEvent.subscribe(function(){if(_14.indexOf("?")>=0){_14=_14.replace(/^.*\?/,"#");}else{_14="";}
dhtmlHistory.add(_14,["Widgets.DataTable.historyChanged",this._listName]);},this,true);_15.startEvent.subscribe(Widgets.DataTable.li.start,Widgets.DataTable.li,true);_15.finalizeEvent.subscribe(Widgets.DataTable.li.stop,Widgets.DataTable.li,true);_15.URL=url;_15.getContent();YAHOO.util.Event.stopEvent(e);return false;},this,true);}};Widgets.DataTable.historyChanged=function(_16,_17){var _18=YAHOO.util.Dom.get(_17);var url=window.location.href.replace(/\?.*$/,"");url=url.replace(/#.*$/,"");url+="?KT_data_request="+_18.id;url+="&"+_16;this.domElement=_18;var _1a=new Kore.HtmlProvider(null,this);_1a.startEvent.subscribe(Widgets.DataTable.li.start,Widgets.DataTable.li,true);_1a.finalizeEvent.subscribe(Widgets.DataTable.li.stop,Widgets.DataTable.li,true);_1a.URL=url;_1a.getContent();};Widgets.DataTable.handleFormSubmit=function(e){var _1c;if(typeof fire_starter=="undefined"||(typeof fire_starter!="undefined"&&!fire_starter)){_1c=YAHOO.util.Event.getTarget(e);}else{_1c=fire_starter;}
if(_1c.form){_1c=_1c.form;}
var uri="&"+Form.serialize(_1c);uri=uri.replace(/&[^&]*=&/g,"&");var url=window.location.href.replace(/\?.*$/,"");url=url.replace(/#.*$/,"");url+="?"+uri.substring(1);var _1f=url;url+="&KT_data_request="+_1c.id;this.domElement=_1c;var _20=new Kore.HtmlProvider(null,this);_20.finalizeEvent.subscribe(function(){if(_1f.indexOf("?")>=0){_1f=_1f.replace(/^.*\?/,"#");}else{_1f="";}
dhtmlHistory.add(_1f,["Widgets.DataTable.historyChanged",_1c.id]);},this,true);_20.startEvent.subscribe(Widgets.DataTable.li.start,Widgets.DataTable.li,true);_20.finalizeEvent.subscribe(Widgets.DataTable.li.stop,Widgets.DataTable.li,true);_20.URL=url;_20.getContent();YAHOO.util.Event.stopEvent(e);return false;};Widgets.DataTable.li=null;