
if(typeof Widgets=="undefined"){Widgets={};}
Widgets.Draggable=Class.create();Widgets.Draggable.prototype={initialize:function(id,_2,_3){this.id=id;this.group=_2;this.options=Object.copy(_3);this.transport=Object.copy(_3.transport);this.hasUpdate=typeof this.options.onCategoryUpdate=="function";this.hasSort=typeof this.options.onSort=="function";Widgets.mayHighlightDND=true;var _4=new Kore.JSLoader();_4.addFile("includes/yui/yahoo/yahoo.js");_4.addFile("includes/yui/dom/dom.js");_4.addFile("includes/yui/event/event.js");_4.addFile("includes/yui/dragdrop/dragdrop.js");_4.addFile("includes/yui/animation/animation.js");_4.addFile("includes/kore/js/error.js");_4.addFile("includes/kore/js/browser/browser.js");_4.loadFiles(function(){if(!Kore.isOkForAjax()){return false;}
if(Kore.is.ie&&(Kore.is.version==6)){try{document.execCommand("BackgroundImageCache",false,true);}
catch(e){}}
Kore.addUnloadListener(this.unload,this);Kore.getIncludesBase(this.render.bind(this),this);_4=null;}.bind(this));},unload:function(){Widgets._proxiesTarget=null;delete this.dd;},createGhost:function(){if(!Widgets._proxiesTarget){var _5=YAHOO.util.Dom.get(this.id);var _6=_5;var _7=null;while(_6){if(/_dropzone/.test(""+_6.id)){_7=_6;}
if(_7&&!/_dropzone/.test(""+_6.id)){break;}
_6=_6.parentNode;}
var _8=_7||_5;Widgets._proxiesTarget=_8.parentNode||_8;}
var el=document.createElement("div");el.id=this.id+"_drag_proxy";el.className="drag_proxy";Widgets._proxiesTarget.insertBefore(el,Widgets._proxiesTarget.firstChild);},makeUniqueId:function(){var _a=function(){return("el_"+Math.random().toString().replace(/\./,""));};var ui=_a();while(YAHOO.util.Dom.get(ui)){ui=_a();}
return ui;},render:function(){this.createGhost();this.dd=new YAHOO.util.DDProxy(this.id,this.hasSort?(this.group+"_drop_zones"):this.makeUniqueId());this.dd.dragElId=this.id+"_drag_proxy";this.dd.isListItem=true;this.dd.transport=this.transport;this.target_position="";this.target_pk="";this.target_fk="";this.target_item_id="";this.target_zone_id="";this.item=this.dd.getEl();YAHOO.util.Event.addListener(this.item,"mouseover",function(){if(!Widgets.mayHighlightDND){return;}
YAHOO.util.Dom.addClass(this.item,"drag_item_over");}.bind(this));YAHOO.util.Event.addListener(this.item,"mouseout",function(){if(!Widgets.mayHighlightDND){return;}
YAHOO.util.Dom.removeClass(this.item,"drag_item_over");}.bind(this));var _c=this;this.dd.onMouseDown=function(e){if(_c.dd.dragCurrent){return false;}};this.dd.startDrag=function(x,y){YAHOO.util.Dom.removeClass(_c.item,"drag_item_over");Widgets.mayHighlightDND=false;if(typeof EDIP_closeOpenEditor=="function"){EDIP_closeOpenEditor();}
_c.inprogress=false;if(!_c.hasSort){this.addToGroup(_c.group+"_drop_zones");}
_c.item=this.getEl();_c.shadow=this.getEl().cloneNode(false);_c.shadow.id=_c.makeUniqueId();YAHOO.util.Dom.addClass(_c.shadow,"drag_suggested_position");_c.shadow.innerHTML="<span>"+_c.item.innerHTML+"</span>";YAHOO.util.Dom.setStyle(_c.shadow.firstChild,"opacity",0.3);_c.item.parentNode.insertBefore(_c.shadow,_c.item.nextSibling);YAHOO.util.Dom.addClass(_c.item,"drag_item_selected");var _10=this.getDragEl();_10.innerHTML=""+"<table width=\"100%\" cellpading=\"0\" cellspacing=\"0\" border=\"0\">"+"<tr>"+"<td>"+_c.item.innerHTML+"</td>"+"</tr>"+"</table>";_10.style.visibility="visible";};this.dd.endDrag=function(e){if(!_c.hasSort){this.removeFromGroup(_c.group+"_drop_zones");}
if(_c.oldpos_showtimeout){window.clearTimeout(_c.oldpos_showtimeout);_c.oldpos_showtimeout=null;}
var _12=this.getDragEl();_12.style.visibility="visible";if(_c.newpos_showtimeout){window.clearTimeout(_c.newpos_showtimeout);_c.newpos_showtimeout=null;}
if(_c.lastItemCollision){_c.lastItemCollision=null;}else{_c.repaint();}};this.dd.onDragOut=function(e,id){var _15=YAHOO.util.DDM.getDDById(id);if(_15.isListItem){if(_c.hasSort){_c.lastItemCollision=null;}else{return;}}
if(_c.newpos_showtimeout){window.clearTimeout(_c.newpos_showtimeout);_c.newpos_showtimeout=null;}
window.clearTimeout(_c.oldpos_showtimeout);_c.oldpos_showtimeout=window.setTimeout(function(){_c.item.parentNode.insertBefore(_c.shadow,_c.item.nextSibling);},100);};this.dd.onDragOver=function(e,id){if(_c.oldpos_showtimeout){window.clearTimeout(_c.oldpos_showtimeout);_c.oldpos_showtimeout=null;}
var el=null;var _19=YAHOO.util.DDM.getDDById(id);var _1a=false;if(_19.isListItem){if(_c.hasSort){el=_19.getEl();if(_c.lastItemCollision!=id){_c.lastItemCollision=id;}}else{if(_19.transport.fk==_c.transport.fk){return;}}}else{if(!_c.lastItemCollision){el=YAHOO.util.Dom.get(id+"_droplist");_1a=true;}
if(!_c.hasSort&&_19.store.pk==_c.transport.fk){return;}}
if(_c.newpos_showtimeout){window.clearTimeout(_c.newpos_showtimeout);_c.newpos_showtimeout=null;}
if(el){var _1b=YAHOO.util.Event.getPageY(e);var pos=YAHOO.util.Region.getRegion(el);var _1d=function(){var mid=pos.top+(Math.floor((pos.bottom-pos.top)/2));if(_1b<mid||_1b>=mid&&!_c.hasSort){_c.target_position="before";if(_19.isListItem){el.parentNode.insertBefore(_c.shadow,el);}else{el.insertBefore(_c.shadow,el.firstChild);}}else{_c.target_position="after";if(_19.isListItem){el.parentNode.insertBefore(_c.shadow,el.nextSibling);}else{el.appendChild(_c.shadow);}}};if(_1a){_c.newpos_showtimeout=window.setTimeout(function(){_1d();},10);}else{_1d();}}};this.dd.onDragDrop=function(e,id){if(_c.oldpos_showtimeout){window.clearTimeout(_c.oldpos_showtimeout);_c.oldpos_showtimeout=null;}
if(_c.newpos_showtimeout){window.clearTimeout(_c.newpos_showtimeout);_c.newpos_showtimeout=null;}
var _21=YAHOO.util.DDM.getDDById(id);if(_21.isListItem){if(_c.hasSort){_c.target_pk=_21.transport.pk;_c.target_fk=_21.transport.fk;_c.target_item_id=id;_c.target_zone_id="";}}else{if(_c.target_item_id==""){_c.target_pk="";}
_c.target_fk=_21.store.pk;_c.target_zone_id=id;if(_c.transport.fk==_c.target_fk){if(_c.hasSort){_c.options.onSort(_c.transport.pk,_c.transport.fk,_c.target_pk,_c.target_position,_c.finalizeSortUpdate.bind(_c));}else{_c.finalizeSortUpdate("update",[{content:"OK"}]);}}else{if(_c.hasUpdate){_c.options.onCategoryUpdate(_c.transport.pk,_c.target_fk,_c.finalizeCategoryUpdate.bind(_c));}else{_c.finalizeCategoryUpdate("update",[{content:"OK"}]);}}}};},finalizeSortUpdate:function(_22,_23){var _24=_23[0];if(_24.error){_24.error.show("Error no: %s has occured: \"%s"+"\" while executing query to URL: \""+_24.URL+"\".");this.fail();}else{if(_24.content.error){Kore.Log.info("Error: "+_24.content.error.message);this.fail();}else{var _25=_24.content;if(_25=="OK"){this.repaint();this.target_position="";this.target_pk="";this.target_fk="";this.target_item_id="";this.target_zone_id="";}}}},finalizeCategoryUpdate:function(_26,_27){var _28=_27[0];if(_28.error){_28.error.show("Error no: %s has occured: \"%s"+"\" while executing query to URL: \""+_28.URL+"\".");this.fail();}else{if(_28.content.error){Kore.Log.info("Error: "+_28.content.error.message);this.fail();}else{var _29=_28.content;if(_29=="OK"){this.transport.fk=this.target_fk;if(this.hasSort){this.options.onSort(this.transport.pk,this.transport.fk,this.target_pk,this.target_position,this.finalizeSortUpdate.bind(this));}else{this.finalizeSortUpdate("update",[{content:"OK"}]);}}}}},fail:function(){this.target_position="";this.target_pk="";this.target_fk="";this.target_item_id="";this.target_zone_id="";this.item.parentNode.insertBefore(this.shadow,this.item.nextSibling);this.repaint();},validateRegion:function(_2a){return(!isNaN(_2a.top+_2a.right+_2a.bottom+_2a.left));},repaint:function(){if(this.inprogress){return;}
this.inprogress=true;this.shadow.style.display="";var _2b=YAHOO.util.Region.getRegion(this.shadow);var _2c=this.dd.getDragEl();var _2d=YAHOO.util.Region.getRegion(_2c);if(this.target_item_id||this.target_zone_id){this.shadow.parentNode.insertBefore(this.item,this.shadow);var _2e=new YAHOO.util.Anim(_2c,{top:{by:_2b.top-_2d.top},left:{by:_2b.left-_2d.left},width:{to:_2b.right-_2b.left},height:{to:_2b.bottom-_2b.top},opacity:{to:1}},0.5,YAHOO.util.Easing.easeOut);}else{var _2e=new YAHOO.util.Motion(_2c,{points:{to:[_2b.left,_2b.top]}},0.3,YAHOO.util.Easing.easeOut);}
_2e.onComplete.subscribe(this.animation_done,this,true);_2e.animate();},animation_done:function(){Widgets.mayHighlightDND=true;var _2f=this.dd.getDragEl();_2f.style.visibility="hidden";this.shadow.style.display="none";YAHOO.util.Dom.removeClass(this.item,"drag_item_selected");YAHOO.util.Dom.removeClass(this.shadow,"drag_suggested_position");var _30=this.shadow.parentNode;_30.replaceChild(this.item,this.shadow);}};Widgets.DropZone=Class.create();Widgets.DropZone.prototype={initialize:function(id,_32,_33){this.id=id;this.group=_32;this.store=Object.copy(_33.store);var _34=new Kore.JSLoader();_34.addFile("includes/yui/yahoo/yahoo.js");_34.addFile("includes/yui/dom/dom.js");_34.addFile("includes/yui/event/event.js");_34.addFile("includes/yui/dragdrop/dragdrop.js");_34.addFile("includes/kore/js/error.js");_34.addFile("includes/kore/js/browser/browser.js");_34.loadFiles(function(){Kore.getIncludesBase(this.render.bind(this),this);delete _34;}.bind(this));},render:function(){this.dd=new YAHOO.util.DDTarget(this.id,this.group+"_drop_zones");this.dd.isListItem=false;this.dd.store=Object.copy(this.store);}};Widgets.makeDraggables=function(_35,_36,_37){_37=_37||{};for(var id in _36){_37.transport=_36[id];new Widgets.Draggable(id,_35,_37);}};Widgets.makeDropZones=function(_39,_3a,_3b){_3b=_3b||{};for(var id in _3a){_3b.store=_3a[id];new Widgets.DropZone(id,_39,_3b);}};