
if(typeof Widgets=="undefined"){Widgets={};}
Widgets.Tooltip=Class.create();Widgets.Tooltip.prototype={contentCallback:null,_url:null,initialize:function(_1,_2,_3,_4,_5){this._triggerElementID=_1;this._triggerElement=YAHOO.util.Dom.get(_1);if(typeof _2!="undefined"){this._url=$app_path+"?"+encodeURI(_2)+"__state="+encodeURI(_3);for(var i=0;i<_4.length;i++){this._url+="&"+encodeURI(_4[i].name)+"="+encodeURI(_4[i].value);}
this._url+="&KT_ajax_request=true";this._url+="&KT_tooltip=true";}
this.domElement=null;this.dims=null;if(typeof _5!="undefined"){if(_5.width!=""&&_5.height!=""){this.dims=_5;}}
this._xy=[0,0];this._lastxy=[0,0];this._shouldBeVisible=false;this._loading=false;Widgets.Tooltip.tooltipsHash.push(this);YAHOO.util.Event.addListener(this._triggerElement,"mouseover",this._mouseOverTrigger,this,true);YAHOO.util.Event.addListener(this._triggerElement,"mouseout",this._mouseOutTrigger,this,true);YAHOO.util.Event.addListener(this._triggerElement,"click",this._clickTrigger,this,true);YAHOO.util.Event.addListener(this._triggerElement,"mousemove",this._mouseOverTrigger,this,true);},_mouseOverTrigger:function(e){this._xy=YAHOO.util.Event.getXY(e);this._xy[1]+=21;this._shouldBeVisible=true;this._refreshTimeout();},_mouseOutTrigger:function(){this._shouldBeVisible=false;this._refreshTimeout();},_clickTrigger:function(){this._shouldBeVisible=false;this._refreshTimeout();},_mouseOverTooltip:function(){this._xy[0]=this._lastxy[0];this._xy[1]=this._lastxy[1];this._shouldBeVisible=true;this._refreshTimeout();},_mouseOutTooltip:function(){this._shouldBeVisible=false;this._refreshTimeout();},_refreshTimeout:function(){if(Widgets.Tooltip._to!=null){clearTimeout(Widgets.Tooltip._to);Widgets.Tooltip._to=null;}
Widgets.Tooltip._to=setTimeout("Widgets.Tooltip.refreshAll()",300);},refreshView:function(){if(this._shouldBeVisible){this._showTooltip();}else{this._hideTooltip();}},_hideTooltip:function(){if(this.domElement!=null){this.domElement.style.display="none";}},_showTooltip:function(){if(this.domElement==null){this._loading=true;this.domElement=document.createElement("div");this.domElement.id="_tooltip_"+this._triggerElementID;YAHOO.util.Dom.addClass(this.domElement,"panel_tooltip");document.body.appendChild(this.domElement);this.domElement.style.zIndex=10000;if(this.dims!=null){this.domElement.style.width=this.dims.width+"px";this.domElement.style.height=this.dims.height+"px";this.domElement.style.overflow="hidden";}
YAHOO.util.Event.addListener(this.domElement,"mouseover",this._mouseOverTooltip,this,true);YAHOO.util.Event.addListener(this.domElement,"mouseout",this._mouseOutTooltip,this,true);if(this._url!=null){var _8=new Kore.HtmlProvider(this._url,this);_8.finalizeEvent.subscribe(function(){this._loading=false;this._showTooltip();},this,true);_8.getContent();}else{this._loading=false;this._showTooltip();}}else{if(this._shouldBeVisible&&!this._loading){if(this.contentCallback!=null){this.domElement.innerHTML=this.contentCallback(this._triggerElementID);if(this.domElement.innerHTML==""){return;}}
this.domElement.style.left=(this._xy[0])+"px";this.domElement.style.top=(this._xy[1])+"px";this._lastxy[0]=this._xy[0];this._lastxy[1]=this._xy[1];this.domElement.style.display="block";}}},checkDestroyed:function(){if(this._triggerElement&&this._triggerElement.parentNode==null){if(this.domElement!=null){document.body.removeChild(this.domElement);}
return true;}
return false;},unload:function(){}};Widgets.Tooltip.tooltipsHash=[];Widgets.Tooltip._to=null;Widgets.Tooltip.refreshAll=function(){for(var i=0;i<Widgets.Tooltip.tooltipsHash.length;i++){if(Widgets.Tooltip.tooltipsHash[i].checkDestroyed()){Widgets.Tooltip.tooltipsHash.splice(i,1);i--;}else{Widgets.Tooltip.tooltipsHash[i].refreshView();}}};